# Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,21,4,5]], np.int32)

In [3]:
myarr

array([[ 1, 21,  4,  5]])

In [4]:
myarr[0,0]

1

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,0]=33

In [8]:
myarr

array([[33, 21,  4,  5]])

**Array Creation : Conversion from other Python Structures**

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

**Array Creation : Intrinsic numpy array array creation objects**

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
zeros.size

10

In [20]:
rng = np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace = np.linspace(1,5,4)

In [23]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.11260483e-306,
        7.56587584e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
arr = np.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr = arr.reshape(3,33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr = arr.ravel()

In [37]:
arr.shape

(99,)

In [38]:
#Concept of Axis

#          col-0  col-1  col-2   sum(axis=1)
#row-0 ->    1       2      3      6
#row-1 ->    4       5      6      15
#row-2 ->    7       1      0      8
    
#sum(axis=0) 12      8      9

#1D Array --> one axis - axis0
#2D Array --> two axis - axis0 , axis1

#axis0 is along rows
#axis1 is along columns

In [39]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [40]:
ar = np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.sum(axis=0) #see above comment cell

array([12,  8,  9])

In [43]:
ar.sum(axis=1) #see above comment cell

array([ 6, 15,  8])

In [44]:
ar.T #Transpose of array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar.flat #work as a itrator

In [46]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
ar.ndim #return number of dimensions

2

In [48]:
ar.size #number of elements

9

In [49]:
ar.nbytes #total bytes consumed

36

In [50]:
one = np.array([1,3,4,634,2])

In [51]:
one.argmax() #index of maximum element

3

In [52]:
one.argmin() #index of minimum element

0

In [53]:
one.argsort() #index of sorted array

array([0, 4, 1, 2, 3], dtype=int64)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar.argmin() # It takes it as a straight array and count the index normally

8

In [56]:
ar.argmax() # It takes it as a straight array and count the index normally

6

In [57]:
ar.argmax(axis=0) #max element in axis0

array([2, 1, 1], dtype=int64)

In [58]:
ar.argmax(axis=1) #max element in axis1

array([2, 2, 0], dtype=int64)

In [59]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [60]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [61]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [62]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [66]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [67]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [69]:
ar.sum() #sum of all elements

29

In [70]:
ar.max() #maximum of all elements

7

In [71]:
ar.min() #minimum of all elements

0

In [72]:
np.where(ar>5)

#(array([1, 2], dtype=int64), array([2, 0], dtype=int64))
#array [1,2] means at row=1 and col=2, element is >5
#array [2,0] means at row=2 and col=0, element is >5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [73]:
type(np.where(ar>5)) # np.where() returns tuple of desired condition. 

tuple

In [74]:
np.count_nonzero(ar) # no. of non-zero elements.

8

In [75]:
np.nonzero(ar) #return index of nonzero elements on each axis

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [76]:
import sys

In [77]:
py_ar = [0,4,55,2]

In [78]:
np_ar = np.array(py_ar)

In [79]:
sys.getsizeof(1) * len(py_ar) #size taken by normal list in python

112

In [80]:
np_ar.itemsize * np_ar.size #size taken by Numpy array

16

In [81]:
np_ar.tolist() #convert numpy array to python list

[0, 4, 55, 2]